version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - ollama
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./backend:/app
    restart: on-failure

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: streamlit-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: on-failure

volumes:
  ollama:
